### ISSUE TITLE
I would like to be able to choose filetypes to download.

### ISSUE THREAD

**Issue by rlitsetorp** [mysteryengineer/reddit-downloader#3]
It would be great if it were possible to set which file types should be downloaded. For example: -e REDDIT_FILETYPES=("jpg", "jpeg") and so on, also that these are independent of lower or upper case.

**Comment by vegidio** [comment]
This is probably an easy change. I will try to work on this after the holidays.

**Comment by rlitsetorp** [comment]
Wow, fast answer! You got a star from me, i really like the project!

**Comment by vegidio** [comment]
This change is now available in the release [24.1.2](https://github.com/mysteryengineer/reddit-downloader/releases/tag/24.1.2)

---

### File filtering

You can filter the files that you want to download based on their extension, separated by comma. To do that you must:

- **CLI tool:** add the parameter `--extensions`; for example: `--extensions jpg,jpeg`. 

- **Docker:** add the environment variable `-e REDDIT_EXTENSIONS`; for example: `-e REDDIT_EXTENSIONS=jpg,jpeg`.
