### ISSUE TITLE
I would like to be able to choose multiple users to download.

### ISSUE THREAD

**Issue by 0x20Fearless** [mysteryengineer/reddit-downloader#5]
It would be great if it were possible to set multiple usernames and have it download more at once, or in a batch. For example: -e REDDIT_NAME=Pizzacakecomic,Smartastic 

Then it makes both folders, and works as per usual.
Maybe with an extra -e : MULTIPLE_ACCOUNTS=yes 

Thank you!

**Comment by vegidio** [comment]
This is a good idea and I can implement this. However, I just started the development of a new app that will download media files not only from Reddit, but also from other websites, so I will include this new feature there.

If you want you can follow the development of that new app [here](https://github.com/vegidio/umd-app). It should be ready in around 1 month.
