### ISSUE TITLE
Grab mp4 instead of gif

### ISSUE THREAD

**Issue by eldepor** [mysteryengineer/reddit-downloader#6]
Hi, would be possible any way to grab the mp4 file instead of gif from some users posts?  In a browser, when you right click a gif and choose save video as, sometimes it would be saved as mp4 instead of gif, which saves a lot of space. Even in jdownloader you can grab both the gif and the mp4 file. 

Thanks

**Comment by vegidio** [comment]
Yes, I'm planning to work on this in the next 1-2 months. My focus now is a GUI for the app, but this should come next.

**Comment by eldepor** [comment]
Awesome thanks
